name: ci

enable-email-notifications: true

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"

jobs:
  workstation:
    runs-on: self-hosted
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Fix for bad os check
        run: echo "RUNNER_OS=Linux" >> $GITHUB_ENV
      - name: Login to Forgejo Registry
        uses: https://cremin.dev/actions/podman-login@v1
        with:
          registry: cremin.dev
          username: ${{ vars.FORGEJO_REGISTRY_USER }}
          password: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}
          auth_file_path: /run/user/1001/containers/auth.json
      - name: Check out repository
        uses: https://cremin.dev/actions/checkout@v4
      - name: Get commit message
        id: commit_message
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
      - name: Fetch latest image
        run: |
          podman pull ghcr.io/ublue-os/silverblue-main:42
      - name: Build image
        uses: https://cremin.dev/actions/buildah-build@v2
        with:
          containerfiles: ./workstation/Containerfile
          context: ./workstation
          image: cremin.dev/jonathan/ublue-silverblue-main
          tags: 42 latest 42-${{ env.NOW }}
          build-args: |
            SOURCE_IMAGE=ghcr.io/ublue-os/silverblue-main
            FEDORA_MAJOR_VERSION=42
            NVIDIA_BUILD=false
      - name: Push image
        uses: https://cremin.dev/actions/push-to-registry@v2
        with:
          registry: cremin.dev
          username: ${{ vars.FORGEJO_REGISTRY_USER }}
          password: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}
          image: jonathan/ublue-silverblue-main
          tags: 42 latest 42-${{ env.NOW }}
      - name: Delete local image
        run: podman rmi jonathan/ublue-silverblue-main:42 jonathan/ublue-silverblue-main:latest jonathan/ublue-silverblue-main:42-${{ env.NOW }}
  workstation-nvidia:
    runs-on: self-hosted
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Fix for bad os check
        run: echo "RUNNER_OS=Linux" >> $GITHUB_ENV
      - name: Login to Forgejo Registry
        uses: https://cremin.dev/actions/podman-login@v1
        with:
          registry: cremin.dev
          username: ${{ vars.FORGEJO_REGISTRY_USER }}
          password: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}
          auth_file_path: /run/user/1001/containers/auth.json
      - name: Check out repository
        uses: https://cremin.dev/actions/checkout@v4
      - name: Get commit message
        id: commit_message
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
      - name: Fetch latest image
        run: |
          podman pull ghcr.io/ublue-os/silverblue-nvidia:42
      - name: Build image
        uses: https://cremin.dev/actions/buildah-build@v2
        with:
          containerfiles: ./workstation/Containerfile
          context: ./workstation
          image: cremin.dev/jonathan/ublue-silverblue-nvidia
          tags: 42 latest 42-${{ env.NOW }}
          build-args: |
            SOURCE_IMAGE=ghcr.io/ublue-os/silverblue-nvidia
            FEDORA_MAJOR_VERSION=42
            NVIDIA_BUILD=true
      - name: Push image
        uses: https://cremin.dev/actions/push-to-registry@v2
        with:
          registry: cremin.dev
          username: ${{ vars.FORGEJO_REGISTRY_USER }}
          password: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}
          image: jonathan/ublue-silverblue-nvidia
          tags: 42 latest 42-${{ env.NOW }}
      - name: Delete local image
        run: podman rmi jonathan/ublue-silverblue-nvidia:42 jonathan/ublue-silverblue-nvidia:latest jonathan/ublue-silverblue-nvidia:42-${{ env.NOW }}
